name: Manylinux Build

on:
  workflow_dispatch:

jobs:
  manylinux:
    runs-on: ubuntu-latest
    container:
      image: quay.io/pypa/manylinux2014_x86_64
      options: --user root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: |
          pip install maturin auditwheel

      - name: Build wheels with maturin
        run: |
          maturin build --release --out dist --manylinux 2014 --find-interpreter

      - name: Repair wheels using auditwheel
        run: |
          auditwheel repair --plat manylinux2014_x86_64 dist/*.whl -w dist/

      - name: Upload manylinux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: wheels-manylinux2014_x86_64
          path: dist 